from pyray import *
from random import randint, uniform
from os.path import join

WINDOW_WIDTH = 800
WINDOW_HEIGHT = 450
WINDOW_TITLE = "survival: pang"
TARGET_FPS = 60

PLAYER_BASE_SIZE = 20.0
PLAYER_SPEED = 4.0
PLAYER_JUMP_FORCE = -12.0
PLAYER_GRAVITY = 0.35

BALL_SIZES = [40.0, 28.0, 18.0]
BALL_SMALL_RADIUS = 18.0
BALL_BASE_SPEED = 2.5

BALL_SPLIT_TIME_MIN = 5.0
BALL_SPLIT_TIME_MAX = 10.0

BALL_DISAPPEAR_TIME_MIN = 4.0
BALL_DISAPPEAR_TIME_MAX = 8.0

BOUNCE_RANDOM_MIN = 0.8
BOUNCE_RANDOM_MAX = 1.4

PLATFORM_WIDTH = 120.0
PLATFORM_HEIGHT = 12.0
PLATFORM_SPEED_MIN = 1.5
PLATFORM_SPEED_MAX = 3.5
PLATFORM_SPAWN_INTERVAL = 5.0
PLATFORM_Y_MIN = 0.52
PLATFORM_Y_MAX = 0.72

GROUND_HEIGHT = 20