from pyray import *
from random import randint, uniform
from os.path import join

# Settings for Pang game
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 450
WINDOW_TITLE = "classic game: pang"
TARGET_FPS = 60

PLAYER_BASE_SIZE = 20.0
PLAYER_SPEED = 5.0
PLAYER_MAX_SHOOTS = 1
PLAYER_MAX_LIFE = 3

MAX_BIG_BALLS = 2
BALLS_SPEED = 2.0

GAME_SPEED = 1.0
POWERUP_SPEED = 100.0

# Ball sizes
BIG_BALL_RADIUS = 40.0
MEDIUM_BALL_RADIUS = 20.0
SMALL_BALL_RADIUS = 10.0

# Ball points
BIG_BALL_POINTS = 200
MEDIUM_BALL_POINTS = 100
SMALL_BALL_POINTS = 50